Vagrant.configure("2") do |config|
  # https://portal.cloud.hashicorp.com/vagrant/discover/debian/bookworm64
  config.vm.box = "debian/bookworm64"

  # server
  config.vm.define "tbrandtS" do |server|
    server.vm.hostname = "tbrandtS"
    # eth1
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "./server.sh", args: ["192.168.56.110"]
  end

  # worker
  config.vm.define "tbrandtSW" do |worker|
    worker.vm.hostname = "tbrandtSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "./worker.sh", args: ["192.168.56.110"]
  end
end
